//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDocumentsGenerate.WsGenerarPDFReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsGenerarPDFReference.IWsGenerarPDFexterno")]
    public interface IWsGenerarPDFexterno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGenerarPDFexterno/CargaDocumentoExterno", ReplyAction="http://tempuri.org/IWsGenerarPDFexterno/CargaDocumentoExternoResponse")]
        string CargaDocumentoExterno(string informacionDocumentos, string informacionUsuarios, string rutaDirectorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGenerarPDFexterno/CargaDocumentoExterno", ReplyAction="http://tempuri.org/IWsGenerarPDFexterno/CargaDocumentoExternoResponse")]
        System.Threading.Tasks.Task<string> CargaDocumentoExternoAsync(string informacionDocumentos, string informacionUsuarios, string rutaDirectorio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsGenerarPDFexternoChannel : ServiceDocumentsGenerate.WsGenerarPDFReference.IWsGenerarPDFexterno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGenerarPDFexternoClient : System.ServiceModel.ClientBase<ServiceDocumentsGenerate.WsGenerarPDFReference.IWsGenerarPDFexterno>, ServiceDocumentsGenerate.WsGenerarPDFReference.IWsGenerarPDFexterno {
        
        public WsGenerarPDFexternoClient() {
        }
        
        public WsGenerarPDFexternoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGenerarPDFexternoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGenerarPDFexternoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGenerarPDFexternoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CargaDocumentoExterno(string informacionDocumentos, string informacionUsuarios, string rutaDirectorio) {
            return base.Channel.CargaDocumentoExterno(informacionDocumentos, informacionUsuarios, rutaDirectorio);
        }
        
        public System.Threading.Tasks.Task<string> CargaDocumentoExternoAsync(string informacionDocumentos, string informacionUsuarios, string rutaDirectorio) {
            return base.Channel.CargaDocumentoExternoAsync(informacionDocumentos, informacionUsuarios, rutaDirectorio);
        }
    }
}
